### ISSUE TITLE
Add parameters for hyperparameterisation

### ISSUE THREAD

**Issue by rcannood** [openproblems-bio/task_cyto_batch_integration#72]
I propose adding this section:

`config.vsh.yaml`:

```yaml
argument_groups:
  - name: Parameters
    arguments:
      - type: integer
        name: --foo
        info:
          optimize:
            type: linear
            lower: 10
            upper: 20
        default: 10
```

And then in the code:

```python
out = harmonypy.run_harmony(
    data_mat=adata_to_correct.layers["preprocessed"],
    meta_data=adata_to_correct.obs,
    vars_use="batch_str",
    foo=par["foo"],
)
```

Sometimes you need an exponential uniform distribution

```yaml
argument_groups:
  - name: Parameters
    arguments:
      - type: double
        name: --foo
        info:
          optimize:
            type: expuniform
            lower: 0.001
            upper: 0.1
        default: 0.01
```
